version: '3.8'
services:

  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    restart: on-failure:5
    ports:
      - '3000:3000'
    command: 
      - /bin/sh
      - -c
      - |
        npx prisma migrate dev
        npm run start:dev


volumes:
  postgres:
